# This is a basic workflow to help you get started with Actions

name: onboard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]  # excludes master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   gitlog:
    runs-on: ubuntu-latest
    container:
      image: enterpriseautomation/tekton.gitlog
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: interrogate git log
        run: /app/main
   owners:
    runs-on: ubuntu-latest
    needs: gitlog
    container:
      image: enterpriseautomation/tekton.codeowners
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update codeowners
        run: /app/main
      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
